---
- name: Run an inline script
  hosts: all
  become: yes
  tasks:
    - name: Execute a sampple inline script
      shell: |
        echo "staring the script"
        uptime
        echo "disk usage"
        df -h
        echo "CPU load"
        top -bn1 | head -n 10
        echo "Script execution completed"
      register: script_out
    - name: Display out
      debug: 
        var: script_out.stdout
