---
- name: Run inline script on VSI and handle output
  hosts: all
  become: yes
  tasks:

    - name: Execute a simple inline script
      shell: |
        set -e
        echo "Starting the script execution on VSI"
        uptime
        df -h
        top -bn1 | head -n 10
        echo "Script execution completed."
      register: script_output
     - name: Display full script output
      debug:
        var: script_output
