---
- name: Fetch server load average
  hosts: all
  become: no
  tasks:

    - name: Get load average
      command: uptime
      register: server_load

    - name: Display server load
      debug:
        msg: "Server Load: {{ server_load.stdout }}"
